pmm-tests/pmm2-client-setup.sh

PMM-3858 Fixing pmm-agent command

---

pmm-tests/pmm-framework.sh

PMM-3909 Adding Percona Server Support with Dockers and Ports

---

pmm-tests/pmm-framework.sh

Path was not being set, updated the path

PMM-3909 Updating the order, setup must be run before configure, Installation changes

---

pmm-tests/pmm-framework.sh

1. Removes Socket Usage
2. Adds Ports, Updates Proxysql setup

PMM-3909 Adding Support for PXC with Proxy SQL Pmm2.0 framework

---

pmm-tests/pmm-framework.sh

added wipe-clients for PMM2 and removed redundant client's configuration

Pmm 4304 wipe clients for pmm2

---

tests/pages/homePage.js
tests/pages/loginPage.js
tests/verifyUpgradePMM_test.js

Tests to execute PMM server upgrade via UI

PMM-4309 Adding Upgrade UI Tests

---

pmm-tests/pmm-framework.sh

Fixes two issues. 
1) Adds MongoDB profiler level to 2 and avoid setting slowmos, this works well
2) Enable slowlog only when the user ask for it, don't act smart.

PMM-4309 Fixing issue in PMM-Framework

---

codecept.json

Fixing an Issue with CERT error for UI tests on Sauce Labs

PMM-5067 Fix problem with SSL Cert on SauceLabs

---

codecept.json
tests/pages/amiInstanceSetupPage.js
tests/verifyInstanceIdAMISetup_test.js

Adding UI Tests for AMI Instance Page Setup, the Group for the test is `@pmm-ami` hence only to be used for AMI UI test run jobs.

PMM-4826 Adding UI tests for AMI instance Setup Page

---

tests/pages/remoteInstancesPage.js
tests/verifyRemoteInstances_test.js

Changes to UI tests because of change in Iframe for adding Remote instances, removing Iframe usage and updating with react-container.

PMM-4826 Adding Remote MySQL addition Test

---

tests/pages/remoteInstancesPage.js

PMM-4826 Updating Locator for Availability Zone

---

tests/pages/pmmInventoryPage.js
tests/verifyRemoteInstances_test.js

Updating Action for Old versions of PMM, before update to react-containers

PMM-5067 Updating Remote Instance Locator

---

pmm-tests/pmm-2-0-bats-tests/generic-tests.bats

added tests for pmm-admin summary commands

PMM-5386 Add CLI tests for `pmm-admin summary`

---

tests/pages/qanPage.js
tests/verifyQAN_test.js
tests/verifyRemoteInstances_test.js

skipped Remote Instances Test for now, split QAN test into smaller ones, removed hardcoded waits in some methods

PMM-5416 Skip/Change UI tests, Break QAN into different Scenarios

---

codecept.json
tests/pages/pmmSettingsPage.js
tests/verifyPMMSettingsPageElements_test.js

created PMM Settings page, added tests for verifying PMM Settings page elements

PMM 5363 UI tests for PMM-Settings Page

---

tests/pages/prometheusExporterStatusPage.js
tests/pages/qanPage.js

PMM-5430 Fixing QAN Results change Filter 

---

tests/pages/pmmSettingsPage.js
tests/verifyPMMSettingsPageElements_test.js
tests/verifyPMMSettingsPageFunctionality_test.js

fixed failing tests, added test for empty data retention field validation message, refactored SettingsPage page object

PMM 5432 Update PMM Settings UI Tests for changes in Retention

---

local.codecept.json
tests/pages/pmmSettingsPage.js
tests/pages/qanPage.js
tests/verifyPMMSettingsPageFunctionality_test.js
tests/verifyQAN_test.js

added tests for Postgres in QAN, tests for Updating/Clearing Alertmanager rules, updated change Metrics resolution test (removed Change Data Retention step)

Pmm 5434 Update QAN UI tests to check Information for Tables in PG

---

pmm-tests/pmm-2-0-bats-tests/generic-tests.bats
pmm-tests/pmm-framework.sh

PMM-T229, PMM-T230, PMM-T231, PMM-T232 are covered by these

PMM-5693 Adding Annotation Support to Framework and CLI tests

---

pmm-tests/pmm-framework.sh

* Remove UI tests
* PMM-5560 Adding Changes for MongoDB setup script

PMM-5560 Adding MongoDb QA Script Setup (#297)

---

pmm-tests/pmm-framework.sh

1.  Default tag set to `dev-latest` when `--dev` option is provided. 
2.  Parameterised percona/perconalab Dockerhub organization name using `docker_org `variable.

Default tag:dev-latest; parameterise Percona/Perconalab Dockerhub org

---

pmm-tests/pmm-framework.sh

some required variables were missed:
log_slow_rate_type=query
log_slow_verbosity=full
log_slow_admin_statements=ON
log_slow_slave_statements=ON
slow_query_log_always_write_time=1
slow_query_log_use_global_control=all
innodb_monitor_enable=all
userstat=1

PMM-6135 added required variables for Percona Server

---

pmm-tests/check_upgrade.sh
pmm-tests/mongodb_query.php
pmm-tests/pmm-2-0-bats-tests/docker-env-variable-tests.bats
pmm-tests/pmm-2-0-bats-tests/generic-tests.bats
pmm-tests/pmm-2-0-bats-tests/ms-specific-tests.bats
pmm-tests/pmm-2-0-bats-tests/pmm-testsuite.sh
pmm-tests/pmm-framework.sh

Changelog:
- added `--setup-client`
- added `--setup-server`

Update with master, installation refactor, ssl flag fix

---

pmm-tests/pmm-2-0-bats-tests/mongodb-tests.bats
pmm-tests/pmm-framework.sh

Revert "PMM-5740 Adding socket support for mongodb in bats and framework"

---

pmm-tests/pmm-2-0-bats-tests/generic-tests.bats
pmm-tests/pmm-2-0-bats-tests/mongodb-tests.bats
pmm-tests/pmm-framework.sh

Update with percona/master

---

pmm-tests/setup-db.sh

Feature: Setup-DB.sh : ms,ps,md,modb,pgsql,pxc

---

pmm-tests/pmm-framework.md

[Work in progress] New PMM-Framework Documentation
@puneet0191 Let me know of improvements, if any.

pmm-framework documentation

---

pmm-tests/pmm-framework.sh

Supports 8.0, 5.7, Slowlog & Performance Schema with Basic workload

PMM-6437 adding --group-replication support for MS/PS 

---

pmm-tests/pmm-framework.sh

* Remove UI tests
* PMM-6437 Adding Support for PS/MS Group Replication
* PMM-6437 Adding Support for MS/PS Group Replication (#346)
* Remove UI tests
* PMM-6437 Adding Support for PS/MS Group Replication
* PMM-6437 Fixing Issue with PS nodes
* PMM-6437 Fixing issues with PS  (#347)
* Remove UI tests
* PMM-6437 Adding Support for PS/MS Group Replication
* PMM-6437 Fixing Issue with PS nodes
* PMM-6437 Fixing PMM-framework

PMM-6624 Adding custom group replication support for UI tests (#351)

---

pmm-tests/pmm-framework.sh

* Remove UI tests
* PMM-6624 Adding missing library in case for mongo 4.4

PMM-6624 Fixing mongodb 4 4 issue with library  (#350)

---

pmm-tests/minikube_operators_setup.sh
pmm-tests/pmm-framework.sh

Following: https://github.com/percona/pmm-doc/blob/master/docs/setting-up/server/dbaas.md

PMM-7304 minikube operator setup script

---

pmm-tests/check_client_upgrade.sh

Client exporter checks

---

pmm-tests/pmm-2-0-bats-tests/generic-tests.bats

PMM-7627 update the number of log files due to removal

---

pmm-tests/pmm-2-0-bats-tests/pmm-testsuite.sh
pmm-tests/pmm-framework.sh

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-testsuite/detail/pmm2-testsuite/6965/pipeline

PMM-fix cleanup

---

pmm-tests/dbdeployer_setup_status_check.sh
pmm-tests/pmm-framework.sh
pmm-tests/postgres/pgsql-setup-for-extensions-custom-queries.sql

To be used with ui tests job for custom queries for postgresql

PMM-8625 adding dummy queries for pgsql

---

pmm-tests/pmm-2-0-bats-tests/pmm-admin-unregister-tests.bats

pmm-admin appends a custom error message to server response only after 401 HTTP status code.

PMM-8259 Update custom message for server error

---

pmm-tests/pmm-framework.sh

This will help us add and remove DB's dynamically during UI tests execution.

PMM-7425 adding custom service name and clean up option to framework 

---

pmm-tests/check_upgrade.sh

Revert "PMM-9259 custom plugin bug check skip"

---

pmm-tests/pmm-2-0-bats-tests/pdpgsql-tests.bats

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-testsuite/detail/pmm2-testsuite/8126/pipeline

Add-database-tag-to-pmm-admin-add-postgresql-help

---

pmm-tests/mongodb_user_setup.js
pmm-tests/pmm-2-0-bats-tests/modb-tests.bats
pmm-tests/pmm-2-0-bats-tests/pmm-testsuite.sh
pmm-tests/pmm-framework.sh

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-testsuite/detail/pmm2-testsuite/8257/pipeline/45

PMM-7 Fix setup issue with modb and testsuite

---

pmm-tests/pmm-framework.sh

Revert "PMM-5279"

---

pmm-tests/pmm-2-0-bats-tests/docker-env-variable-tests.bats
pmm-tests/pmm-framework.sh

https://pmm.cd.percona.com/job/pmm2-testsuite/8999/

PMM-7 fix installation clickhouse

---

pmm-tests/check_upgrade.sh
pmm-tests/pg_stat_monitor_setup.sh
pmm-tests/pgsql_pgsm_setup.yml

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/detail/pmm2-upgrade-tests/16659/pipeline/100

PMM-9999 Adding check for VM version on docker-way and OVF upgrade

---

pmm-tests/pg_stat_monitor_setup.sh

1) Updated script to enable install from PPG distributions.
2) Removed install of needless dependencies.
3) Removed needless steps.

PMM-9951: Update the pg_stat_monitor setup

---

pmm-tests/backup/ps_57_bm.yml
pmm-tests/backup/ps_80_bm.yml

* fix pmm-agent permission issues for backup managment

Add part when pmm-agent run as root

---

pmm-tests/check_upgrade.py

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/detail/pmm2-upgrade-tests/23848/pipeline

PMM-7 Upgrade VM version

---

pmm-tests/pmm-framework.sh

PR to resolve comment in https://github.com/percona/pmm-ui-tests/pull/493

PMM-7 create db in pgsql setup

---

pmm-tests/check_upgrade.py

Revert "PMM-11368 When upgrading pmm-server from 2.33 to 2.34 victoria metric…"

---

pmm-tests/pmm-2-0-bats-tests/helm-test.bats

PMM-11164
Test for https://github.com/percona/percona-helm-charts/pull/196
Doc: 
- https://two-35-0-pr-984.onrender.com/setting-up/server/helm.html
- https://github.com/percona/pmm-doc/pull/984
Workflow changes:  https://github.com/Percona-Lab/pmm-submodules/pull/3058

PMM-11164 helm backup tests

---

pmm-integration/.eslintrc
pmm-integration/availableArgs.ts
pmm-integration/helpers/commandLine.ts
pmm-integration/helpers/docker.ts
pmm-integration/helpers/setupParameters.interface.ts
pmm-integration/helpers/validateArgs.ts
pmm-integration/integration-setup.ts
pmm-integration/mongoDb/addClientMoDB.ts
pmm-integration/mongoDb/mongo_replica_for_backup/mongoReplicaForBackup.ts
pmm-integration/mongoDb/mongodb_user_setup copy.js
pmm-integration/mysql/addClientPs/addClientPs.ts
pmm-integration/otherConfigs/clearAllSetups.ts
pmm-integration/otherConfigs/installDockerCompose.ts
pmm-integration/package-lock.json
pmm-integration/package.json
pmm-integration/pmmClient/pmm2ClientTarbal.ts
pmm-integration/pmmServer/pmmServerSetup.ts
pmm-integration/postgres/addClientPdPgsql.ts
pmm-integration/postgres/pgsql_pgsm_setup/setup_pmm_pgsm_integration.ts
pmm-integration/tsconfig.json

new Flag addclient=modb,1
Change in file
pmm-integration/mongoDb/addClientMoDB.ts
Other changes are adding of lint.

PMM-11331 Add flag addclient=modb,1

---

pmm-tests/client_container_proxysql_setup.sh
pmm-tests/client_container_pxc_setup.sh
pmm-tests/pxc_proxysql_setup.yml

-- Add ProxySQL admin config
-- Route traffic through proxySQL

Improvements to get ProxySQL working

---

pmm-tests/pmm-pxc-container-integration-setup.sh

Adding pxc-pmm integration setup using separate docker containers.
Additional Proxysql with PXC.
Basic Sysbench tests.

Script to setup pmm-pxc integration separate containers.

---

pmm-tests/pmm-framework.sh

Latest PS Binary
Write only to writers - single primary
Sysbench support
Admin password support

Fixes for GR

---

pmm-tests/client_container_ms_setup.sh
pmm-tests/ms_pmm_setup.yml
pmm-tests/pmm-framework.sh
pmm-tests/product_version_download_helper

Supports Single Server
Supports GR nodes
Supports mutiple Servers

Changes to move MS setup to Playbook

---

pmm-tests/pmm-framework.sh
pmm-tests/pxc_proxysql_setup.yml

UI Nightly tests : https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-test-nightly/detail/pmm2-ui-test-nightly/1930/pipeline/ ( no new failures)
CLI tests in GH: https://github.com/Percona-Lab/pmm-submodules/actions/runs/5505176644/jobs/10032215284 ( no new failures)

Fix PXC to start more than one instance

---

pmm-tests/pgsql_pgsm_setup.yml
pmm-tests/pmm-framework.sh

https://jira.percona.com/secure/Tests.jspa#/testCase/2261
Local test runs end-2-end w/ this patch and --use-socker sent, passed [ bash pmm_pgsm_setup.sh -   OK  | 15 passed, 1 skipped   // 21m ] with PG14

Automated Test case for T2261

---

pmm-tests/client_container_pxc_setup.sh

UI changes https://github.com/percona/pmm-ui-tests/pull/685

Update PXC admin credetails for remote access, required for ui tests

---

pmm-tests/product_version_download_helper
pmm-tests/psmdb_setup.sh

ref: https://jira.percona.com/browse/PMM-12549

Update Mongo version

---

pmm-tests/pmm-framework.sh
pmm-tests/product_version_download_helper
pmm-tests/pxc_proxysql_setup.yml

Note: Default behavior proxysql package will be picked now from product_versoin_download_helper file

ProxySQL support for packages and version URL locations

---

pmm-tests/pmm-framework.sh
pmm-tests/psmdb_setup.sh
pmm-tests/psmdb_setup.yml
pmm-tests/tls-ssl-setup/mongodb/mongodb_ssl_setup.sh
pmm-tests/tls-ssl-setup/mongodb_tls_setup.yml

Has been tested locally and on aws-staging-start. Staging is pretty busy so links to jobs will be wiped.
To make sure please click on any of the following links to create a stage and check it:
* [--mo-version=4.4 --setup-mongodb-ssl --pmm2](https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?MO_VERSION=4.4&PMM_QA_GIT_BRANCH=PMM-12773-mongo-version-update&CLIENTS=--setup-mongodb-ssl) 
* [--mo-version=5.0 --setup-mongodb-ssl --pmm2](https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?MO_VERSION=5.0&PMM_QA_GIT_BRANCH=PMM-12773-mongo-version-update&CLIENTS=--setup-mongodb-ssl) 
* [--mo-version=6.0 --setup-mongodb-ssl --pmm2](https://pmm.cd.percona.com/job/aws-staging-start/parambuild/?MO_VERSION=6.0&PMM_QA_GIT_BRANCH=PMM-12773-mongo-version-update&CLIENTS=--setup-mongodb-ssl) …

PMM-12773 update mongo version

---

.github/workflows/fb-integration-suite.yml
.github/workflows/integration-cli-tests.yml
.github/workflows/runner-integration-cli-tests.yml

CLI Test Changes for GITHUB Actions runs [https://github.com/percona/pmm-qa/actions/runs/8971399208]

Changes for PMM3 and new pmm-framework

---

pmm-tests/psmdb_setup.yml

test runs : https://pmm.cd.percona.com/blue/organizations/jenkins/aws-staging-start/detail/aws-staging-start/74592/pipeline/106

Fix PSMDB Ansible permission issue

---

pmm-tests/tls-ssl-setup/mongodb/mongodb_ssl_setup.sh
pmm-tests/tls-ssl-setup/mysql/mysql_ssl_setup.sh
pmm-tests/tls-ssl-setup/postgres/setup_pgsql.sh

Test Runs [https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-upgrade-tests/activity]

Updates for release repo ssl dependencies(v2)

---

.github/workflows/package-test-single.yml
.github/workflows/pmm-version-getter.yml
.github/workflows/runner-package-test.yml

https://github.com/percona/pmm-qa/actions/runs/10006597402

PMM-13234 Fix centos 7 package testing (#709)

---

pmm-tests/pmm-framework.sh

https://pmm.cd.percona.com/job/aws-staging-start/75260/console

PMM7 fix GR Auth

---

pmm-tests/ms_pmm_setup.yml

Test runs [https://pmm.cd.percona.com/job/aws-staging-start/75539/console] , [https://github.com/percona/pmm-qa/actions/runs/10403163629]

Fix MS Binary filter

---

.github/workflows/v3-cron-fb-daily.yml

Todo: remove test cron timing
ref Test run https://github.com/percona/pmm-qa/actions/workflows/v3-cron-fb-e2e-suite.yml

PMM-13366 Update (test) Cron File for V3 daily runs

---

.github/workflows/runner-e2e-upgrade-tests.yml

https://github.com/percona/pmm-qa/actions/runs/10994556718

PMM-7: Remove percona release

---

.github/workflows/runner-package-test.yml

https://github.com/percona/pmm-qa/actions/runs/11950476023

PMM-7: Fix package tests for RC 3 Beta

---

.github/workflows/package-test-matrix.yml
.github/workflows/package-test-single.yml
.github/workflows/runner-package-test.yml

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-package-testing-arm/detail/pmm3-package-testing-arm/160/pipeline/
https://github.com/percona/pmm-qa/actions/runs/11956234485

PMM-7: Fix package tests for V3 Beta

---

.github/workflows/fb-e2e-suite.yml
.github/workflows/integration-cli-tests.yml

https://github.com/percona/pmm-qa/actions/runs/12024249627/job/33519464098

Pmm2 fix defaults for psmdb

---

.github/workflows/fb-e2e-suite.yml
pmm-tests/psmdb_setup.sh
pmm-tests/tls-ssl-setup/mongodb/mongodb_ssl_setup.sh

During release times, try another version
test runs https://pmm.cd.percona.com/job/aws-staging-start/78239/console

Pmm2 fix mongosh

---

.github/workflows/v3-cron-fb-daily.yml

https://github.com/percona/pmm-qa/actions/runs/14033831176

PMM-13803: Adds package tests to daily V3 Cron Job

---

.github/workflows/runner-e2e-tests-codeceptjs.yml
.github/workflows/runner-e2e-tests-playwright.yml
.github/workflows/runner-e2e-tests-podman.yml

https://github.com/percona/pmm-qa/actions/runs/14069864103

PMM-13765: Ubuntu 22.04 for PMM V3

---

.github/workflows/runner-e2e-tests-codeceptjs.yml
.github/workflows/runner-e2e-tests-playwright.yml
.github/workflows/runner-e2e-tests-podman.yml
.github/workflows/runner-e2e-upgrade-tests.yml

https://github.com/percona/pmm-qa/actions/runs/14070486972

PMM-13765: Ubuntu 22.04 for PMM

---

pmm-tests/agent_status.py

https://pmm.cd.percona.com/blue/organizations/jenkins/pmm3-ui-tests-nightly/detail/pmm3-ui-tests-nightly/994/pipeline/

PMM-7: Refactor admin status using python

---

.github/workflows/fb-e2e-suite.yml
.github/workflows/runner-e2e-tests-podman.yml

https://github.com/percona/pmm-qa/actions/runs/17319003406

PMM-7: Fix podman tests
